### ISSUE TITLE
AWS asking for a reason to justify the quota change

### ISSUE THREAD

**Issue by amp9020** [mikeage/stable-diffusion-aws#1]
Not more of an issue with the code, but an issue with AWS.
They are asking the justification for increasing the vCPUs.
Can someone help provide some lingo I can provide back to AWS support?

Instructions in README is to:
"
Before starting, go to https://us-east-1.console.aws.amazon.com/servicequotas/home/services/ec2/quotas and open a support case to raise the maximum number of vCPUs for "All G and VT Spot Instance Requests" to 4 (each g4dn.xlarge machine is 4 vCPUs).
"

**Comment by mikeage** [comment]
Sure, just say "I'd like to use a GPU for Stable Diffusion".

(at work, I've done projects involving hundreds and even thousands of these machines, and then you actually have to talk with them... but for going from the default 0 to 4 (one machine, 4 vCPUs), they don't actually care :-) )
