### ISSUE TITLE
Script will fail on 2 occasions

### ISSUE THREAD

**Issue by knuurr** [mikeage/stable-diffusion-aws#5]
1) Script will fail on custom tmux config

 https://raw.githubusercontent.com/mikeage/dotfiles/master/.tmux.conf -> 404, fails script.
 
 This is easy because it can be just commented out.
 
 
 
 2) Script will fail where `invokeai-configure` is involved because it's apparently no longer available.
 
```text 
sudo: /home/admin/.local/bin/invokeai-configure: command not found
2024-05-16 16:23:11,655 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2024-05-16 16:23:11,655 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2 finished at Thu, 16 May 2024 16:23:11 +0000. Datasource DataSourceEc2Local.  Up 788.10 seconds
```

Since I don't have PhD in SD, can you advise on mitigation for that?

Last time I tried in november, all was ok.

I also used your script from GH (minus tmux config) because I thought that maybe my own, some models and loras etc. was broken but yours also fails.

**Comment by mikeage** [comment]
Good catches; I redid my dotfiles and that one is no longer there! 

As far as invokeai-configure, I haven't actually used this recently. It was written for invoke ai 3.x (or earlier), and I suspect this change with 4.0, but I haven't had a chance to look into it. I'll try to find some time soon to check..

**Comment by mikeage** [comment]
Fixed both. Note that you need to manually install models now; there is no script currently available to do it.
